### ISSUE TITLE
CreditForm validateCode method is executed multiple times

### ISSUE THREAD

**Issue by ermiry** [Djcharles26/credit_card#1]
It seems that the widget **CreditForm** executes its **build** method multiple times, as the logs go crazy and the method **validateCode** is also executed multiple times. This makes it unusable for operations such as an http request.

**Comment by Djcharles26** [comment]
Reviewing code, found that some controllers can be removed. Although there are some problems with Flutter logs, and they are working on that, they comment that some keyboards send multiple logs.
