### ISSUE TITLE
Render Exception is thrown when creating prepay CreditForm

### ISSUE THREAD

**Issue by ermiry** [Djcharles26/credit_card#3]
This error seems to pop up just with type **prepay**

![image](https://user-images.githubusercontent.com/38005609/86469147-73e00e00-bcfe-11ea-9c43-fa90be6967a0.png)

**Comment by Djcharles26** [comment]
When does this error occurs, when you start creating it, or when you confirm

**Comment by Djcharles26** [comment]
I read your error and it seems that you are not using correctly your column size, please check that field
